import CivicEvent from "../models/civicEvent.model.js";

const generateWeatherEvent = async () => {
  const rainfall = Math.floor(Math.random() * 101);

  let severity = "low";
  let eventType = "weather_update";
  let title = "Weather Update";

  if (rainfall >= 70) {
    severity = "high";
    eventType = "heavy_rain";
    title = "Heavy Rain Detected";
  } else if (rainfall >= 40) {
    severity = "medium";
    eventType = "moderate_rain";
    title = "Moderate Rain Detected";
  }

  const event = {
    source: "weather",
    eventType,
    title,
    description: "Synthetic weather data generated by CityPulse.",
    location: {
      latitude: 26.9124,
      longitude: 75.7873,
      address: "Jaipur",
    },
    severity,
    status: "active",
    value: rainfall,
    unit: "mm",
    timestamp: new Date(),
  };

  return CivicEvent.create(event);
};

export default generateWeatherEvent;